USE [master]
GO

/****** Object:  Database [Parqueo_ULACIT]    Script Date: 12/5/2022 5:35:37 PM ******/
CREATE DATABASE [Parqueo_ULACIT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Parqueo_ULACIT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\Parqueo_ULACIT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Parqueo_ULACIT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\Parqueo_ULACIT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Parqueo_ULACIT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Parqueo_ULACIT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET ARITHABORT OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Parqueo_ULACIT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Parqueo_ULACIT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Parqueo_ULACIT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Parqueo_ULACIT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET RECOVERY FULL 
GO

ALTER DATABASE [Parqueo_ULACIT] SET  MULTI_USER 
GO

ALTER DATABASE [Parqueo_ULACIT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Parqueo_ULACIT] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Parqueo_ULACIT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Parqueo_ULACIT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Parqueo_ULACIT] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Parqueo_ULACIT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Parqueo_ULACIT] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Parqueo_ULACIT] SET  READ_WRITE 
GO

